### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by genti94** [ryanbagwell/django-cms-named-menus#5]
Hello Ryan

My name is Gentian and I'm currently working for Divio AG. I installed your add-on to test it, because we want it to be published on the Django-CMS Marketplace. There is a bug however that if you drag and drop your navigation bars and click on "save" it doesn't get saved. But if you use "save and continue editing" instead of "save" it works.

**Comment by ryanbagwell** [comment]
@genti94 hi, sorry for the late reply. I just saw this. I can look into it further.

**Comment by ryanbagwell** [comment]
@genti94 try it now.
